// <auto-generated />
using System;
using BackGrade;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BackGrade.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20230913000208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackGrade.Models.Cliente", b =>
                {
                    b.Property<int>("ID_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CLIENTE"));

                    b.Property<long?>("CNPJ_CLIENTE_JURIDICO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("CPF_CLIENTE_FISICO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("EMAIL_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NM_CLIENTE_FISICO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RZ_SOCIAL_CLIENTE_JURIDICO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SENHA_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TELEFONE_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TP_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.HasKey("ID_CLIENTE");

                    b.ToTable("T_CLIENTE");
                });

            modelBuilder.Entity("BackGrade.Models.Feedback", b =>
                {
                    b.Property<int>("ID_FEEDBACK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_FEEDBACK"));

                    b.Property<string>("ANALISE_FEEDBACK")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DESC_FEEDBACK")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DT_FEEDBACK")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ID_CLIENTE")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NOTA_FEEDBACK")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID_FEEDBACK");

                    b.ToTable("T_FEEDBACK");
                });
#pragma warning restore 612, 618
        }
    }
}
